//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfImmunizedCows
{
    using System;
    using System.Collections.Generic;
    
    public partial class cow
    {
        public cow()
        {
            this.registers = new HashSet<register>();
        }
    
        public long Id { get; set; }
        public long NumberOnCow { get; set; }
        public string PopulatedPlace { get; set; }
    
        public virtual ICollection<register> registers { get; set; }
    }
}