//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfImmunizedCows
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public long Id { get; set; }
        public long CowID { get; set; }
        public long ImmunisationID { get; set; }
        public System.DateTime DateOnImmunization { get; set; }
    
        public virtual cow cow { get; set; }
        public virtual immunization immunization { get; set; }
    }
}